services:
  admin:
    build: ./admin-frontend
    expose:
      - "80"
    volumes:
      - ./admin-frontend:/app
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - admin
      - backend

  frontend:
    build: ./frontend
    expose:
      - "80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tourismdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: