apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nikitawastaken/backend:latest
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: development
        ports:
        - containerPort: 8000
